CREATE DATABASE IF NOT EXISTS seatallocation;
USE seatallocation;

CREATE TABLE IF NOT EXISTS student (
  student_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  roll_no VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  department VARCHAR(100) NOT NULL,
  subject VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS exam_hall (
  hall_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hall_number VARCHAR(50) NOT NULL UNIQUE,
  capacity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS seating (
  seat_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hall_number VARCHAR(50) NOT NULL,
  seat_number VARCHAR(50) NOT NULL,
  roll_no VARCHAR(50) NOT NULL
);
